global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: [":9093"]
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090

  - job_name: cadvisor
    scrape_interval: 5s
    static_configs:
    - targets: [":9092"]
      labels:
        alias: 'cadvisor'

  - job_name: local_cadvisor
    scrape_interval: 5s
    static_configs:
    - targets:
      - cadvisor:8080

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: "node2"
    static_configs:
    - targets: [":9100"]

  - job_name: "mysql_exporter"
    static_configs:
    - targets: ["9104"]

  - job_name: "apache"
    static_configs:
    - targets: [":9144"]

#Alertmanager settings

rule_files:
  - '/etc/prometheus/alert.rules.yml'
